openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /chart:
    get:
      description: Returns pure statistics for all regions
      responses:
        '200':
          description: OK
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Distribution'
                    
  /map:
    get:
      operationId: "getMap"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Maps'

components:
  schemas:
    Distribution:
      type: array
      items:
        $ref: '#/components/schemas/Region'
    Region:
      type: object
      properties:
        name:
          type: string
          enum:
            - victoria
            - new south wales
            - queensland
            - tasmania
            - western australia
            - southe australia
        total:
          type: number
        percentage:
          type: number
    Maps:
      type: object
      properties:
        type:
          type: string
        features:
          type: array
          items:
            $ref: '#/components/schemas/AreaData'
    AreaData:
      type: object
      properties:
        type:
          type: string
        properties:
          $ref: '#/components/schemas/Property'
        geometry:
          $ref: '#/components/schemas/Geometry'
    Property:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        center:
          $ref: '#/components/schemas/Point'
        childNum:
          type: integer
          description: 不知道干嘛的，先放着
          default: 1
    Geometry:
      type: object
      properties:
        type:
          type: string
          enum:
            - polygon
            - line
          default: polygon
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/Point'
    Point:
      type: array
      items:
        type: number
      maxItems: 2
      minItems: 2     
    Error:
      type: object

