# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 10
  - vol_name: demo-vol-1-2
    vol_size: 10
  - vol_name: demo-vol-2-1
    vol_size: 10
  - vol_name: demo-vol-2-2
    vol_size: 10
  - vol_name: demo-vol-3-1
    vol_size: 10
  - vol_name: demo-vol-3-2
    vol_size: 10
  - vol_name: demo-vol-4-1
    vol_size: 10
  - vol_name: demo-vol-4-2
    vol_size: 10

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-1
    volumes: ['demo-vol-1-1', 'demo-vol-1-2']
    flavor: uom.mse.2c9g
  - name: demo-2
    volumes: ['demo-vol-2-1', 'demo-vol-2-2']
    flavor: uom.mse.2c9g
  - name: demo-3
    volumes: ['demo-vol-3-1', 'demo-vol-3-2']
    flavor: uom.mse.2c9g
  - name: demo-4
    volumes: ['demo-vol-4-1', 'demo-vol-4-2']
    flavor: uom.mse.1c4g
    

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: key1
docker_user: ubuntu
couchdb_user: admin
couchdb_password: admin
couchdb_version: '3.0.0'
couchdb_cookie: ''
couchdb_uuid: ''
