- name: git pull
  shell: git pull
  args:
    chdir: CCC/frontend

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: CCC/frontend

- name: remove old image:frontend
  shell: docker rmi frontend
  args:
    chdir: CCC/frontend


- name: Start server
  shell: docker-compose up -d --build
  args:
    chdir: CCC/frontend