- name: remove couchdb container we have
  become: yes
  docker_container:
     name: couchdb
     state: absent

- name: create and start coucdb docker containr
  become: yes
  docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ couchdb_version }}"
    state: started
    ports:
      - "5984:5984"
      #- "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{couchdb_user}}"
      COUCHDB_PASSWORD: "{{couchdb_password}}"